# Generated by Django 2.2.9 on 2021-01-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaloricBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percent_Protein', models.CharField(max_length=1000)),
                ('Percent_Fat', models.CharField(max_length=1000)),
                ('Percent_Carbs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('Safety_Level', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Amount', models.CharField(max_length=1000)),
                ('Unit', models.CharField(max_length=1000)),
                ('Percent_Of_Daily_Needs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=1000)),
                ('Size', models.CharField(max_length=1000)),
                ('Unit', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api_Id', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=500)),
                ('Breadcrumbs', models.CharField(max_length=500)),
                ('Badges', models.CharField(max_length=500)),
                ('Important_Badges', models.CharField(max_length=500)),
                ('Ingredient_Count', models.CharField(max_length=10)),
                ('Generated_Text', models.CharField(max_length=500)),
                ('Ingredient_List', models.CharField(max_length=500)),
                ('Likes', models.CharField(max_length=50)),
                ('Aisle', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=500)),
                ('CaloricBreakdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CaloricBreakdown', to='foods.CaloricBreakdown')),
                ('Ingredients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredients', to='foods.Ingredients')),
                ('Nutrients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nutrients', to='foods.Nutrients')),
                ('Servings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Servings', to='foods.Servings')),
            ],
        ),
    ]
