# Generated by Django 2.2.9 on 2021-02-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210114_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liks', to=settings.AUTH_USER_MODEL),
        ),
    ]
