# Generated by Django 2.2.9 on 2021-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20210208_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
