# Generated by Django 2.2.9 on 2021-02-08 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20210208_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='Fooddislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Foodlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
