# Generated by Django 2.2.9 on 2021-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20210208_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
