# Generated by Django 2.2.9 on 2021-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20210208_1301'),
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='UserDislikes', to='foods.Food'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Userlikes', to='foods.Food'),
        ),
    ]
