# Generated by Django 2.2.9 on 2021-01-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='Areacode',
            new_name='area_code',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='Dislikes',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='Likes',
        ),
        migrations.AddField(
            model_name='consumer',
            name='dislikes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consumers_Dislikes', to='foods.Food'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consumer_Likes', to='foods.Food'),
        ),
    ]
